### ISSUE TITLE
Handlebars 2.0

### ISSUE THREAD

**Issue by vladikoff** [gruntjs/grunt-contrib-handlebars#100]
We need to update to that.

Ref: https://github.com/gruntjs/grunt-contrib-handlebars/pull/99

**Comment by skindc** [comment]
Can you please, please Upgrade this so it handlebars dependency is version 4.

**Comment by jshaffer** [comment]
^+1 Support for handlebars 4 would be great

**Comment by davidcrreis** [comment]
+1

**Comment by matthewgovaere** [comment]
+1 on support for handlebars 4.

**Comment by vladikoff** [comment]
https://github.com/gruntjs/grunt-contrib-handlebars/releases/tag/v0.11.0
