### ISSUE TITLE
Partial registration happening before namespace defined

### ISSUE THREAD

**Issue by lostthetrail** [gruntjs/grunt-contrib-handlebars#127]
Since 0.9x partials are registering before their namespace is defined.

**Comment by pivotal-vanguard** [comment]
bump

**Comment by lazd** [comment]
Fixed and released as `grunt-contrib-handlebars@0.9.3`.

**Comment by lostthetrail** [comment]
@pivotal-vanguard This should be solved at 0.9.3

**Comment by dylanrhysscott** [comment]
This is still causing me problems as of 0.9.3. I am running Handelbars 2.0.0 with grunt-contrib-handlebars 0.9.3

**Comment by lazd** [comment]
@dylanrhysscott can you put together a small test case and provide the output you're getting so we can troubleshoot it?

Also, please triple check your installed version. Thanks!
