### ISSUE TITLE
Add support for Handlebars 3.x

### ISSUE THREAD

**Issue by jacobq** [gruntjs/grunt-contrib-handlebars#136]
This plugin appears to be linked to Handlebars version ^2.0.0, but now version [3.0.0 has been released](https://github.com/wycats/handlebars.js/blob/master/release-notes.md#v300---february-10th-2015). When I tried to use this plugin with the latest Handlebars library I encountered an error when trying to render partials. It looks something like this: `Uncaught TypeError: Cannot assign to read only property 'partial' of name-of-my-partial` in the `invokePartial` function of Handlerbars 3.0.0:

```
        function invokePartial(partial, context, options) {
            options.partial = true;
            ...
```

**Comment by jacobq** [comment]
It would also be nice if one could take advantage of the [precompile interface](http://handlebarsjs.com/reference.html#base-precompile) provided in newer versions of the library.

**Comment by timomayer** [comment]
+1

**Comment by saulhardman** [comment]
+1

**Comment by cagosto** [comment]
+1

**Comment by dougfarre** [comment]
+1

**Comment by AKhotoolev** [comment]
+1

**Comment by jacobq** [comment]
@AKhotoolev, yes, that's the interim solution (e.g. fork the project and point at the new repo manually in package.json) but that's effectively [monkey patching](http://en.wikipedia.org/wiki/Monkey_patch) and isn't desirable in the long-term / for production software.

**Comment by ivanakimov** [comment]
+1

**Comment by samuelgbrown** [comment]
+1

**Comment by craigweston** [comment]
+1

**Comment by johanpoirier** [comment]
+1

**Comment by jeremyhill-up** [comment]
+1

**Comment by mrniggles214** [comment]
+1

**Comment by kristofzerbe** [comment]
+1

**Comment by stmpy** [comment]
+1

**Comment by vladikoff** [comment]
For those who +1'd, see https://github.com/gruntjs/grunt-contrib-handlebars/pull/134

You can either use the PR or resubmit the PR with fixed tests (or at least something that is up to date with `master`)

**Comment by joostory** [comment]
#138

**Comment by themphill** [comment]
@vladikoff Looks like you can close this now, as of https://github.com/gruntjs/grunt-contrib-handlebars/commit/9fa176ac6d23ed87746677016e7cac2974f10225.

Thanks, @joostory!
