### ISSUE TITLE
How to include custom Handlebars helpers

### ISSUE THREAD

**Issue by distinctgrey** [gruntjs/grunt-contrib-handlebars#58]
I'm working in a project, generated with Yeoman generator-backbone.
RequireJS and Handlebars templates. The templates are precompiled with grunt-contrib-handlebars.
This is the handlebars task in Gruntfile.js:

``` javascript
handlebars: {
            compile: {
                options: {
                    namespace: 'HBS',
                    amd: true,
                    processName: function (filename) {
                        return filename
                            .replace(/app\/src\/modules\//, '')
                            .replace(/\.hbs$/, '');
                    }
                },
                files: {
                    '.tmp/scripts/hbs.js': [
                        '<%= yeoman.app %>/src/modules/*/templates/*.hbs'
                    ]
                }
            }
        }
```

I defined a few custom Handlebars helpers.
My main require config looks like this:

``` javascript
require.config({
  paths: {
       ...
        'handlebars': '../vendor/bower/handlebars/handlebars',
        'hbs': '/scripts/hbs',
        'handlebarshelpers': 'core/templates/helpers',
  },

deps: [
        ...
        'handlebarshelpers',
        'main'
    ]
},

```

This works perfectly in dev (using 'grunt server').
But after building, the dist application prints following error to the console:

```
Uncaught Error: Missing helper: 'compare' 
```

Is there any best practice how to include custom helpers with precompiled templates?
Any idea what could be wrong?

**Comment by ipbebnev** [comment]
Still not understood what i need to use Handlebars or handlebars or handlebarsCore. My usage is:
require.js config:
`
  paths: {
    'handlebars': '../vendor/handlebars/handlebars.amd',
    'handlebarsWithHelpers': './helpers/helpers',
}
`
i not use shims, then my helpers file:
`
define([
  'handlebars'
], function (Handlebars) {
  
  // return html entities to tags
  Handlebars.registerHelper('encodeMyString',function(inputData){
    return new Handlebars.SafeString(inputData);
  });

  return Handlebars;
});
`

then my handlebars usage into component:
`
define([
  'handlebarsWithHelpers',',
  'text!templates/job-details-popup.hbs'
], function (
  HandleBars,
  JobDetailsTemplate
) {
// component code here
}
`
