### ISSUE TITLE
Is there anyway to precompile handlebars helpers as well?

### ISSUE THREAD

**Issue by avidal** [gruntjs/grunt-contrib-handlebars#8]
Any chance for a helpers filepath, which will be mixed in when precompiling?

**Comment by kaidoe** [comment]
I recently wanted to do this and modified grunt-contrib-handlebars to pre-compile helpers into the same file (commit: https://github.com/kaidoe/grunt-contrib-handlebars/commit/6494373cad1a2297d717b37491e022373e16ca05).

You pass the helpers to the options hash, here I keep mine in an external file as a node module.

````
options: {
  helpers: require('./lib/templateHelpers.js')
}
````

That commit is a quick try and by no means tested for all cases, but would this be something that people would be interested in?
